export const siteConfig = {
  name: "Serendipity Arts Festival",
  description: "Official website of Serendipity Arts Festival",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  api_base_url: process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://127.0.0.1:8000/api/v1/web",
  cdn_base_url: process.env.NEXT_PUBLIC_CDN_URL ?? "http://127.0.0.1:8000/uploads",
  game_url: process.env.NEXT_PUBLIC_GAME_URL ?? "http://localhost:8080",
  currency: process.env.NEXT_PUBLIC_CURRENCY ?? "INR",
  locale: process.env.NEXT_PUBLIC_CURRENCY_LOCALE ?? "en-IN",
  navigation: [
    { label: "Home", href: "/", comingSoon: false },
    { label: "Programmes", href: "/programmes", comingSoon: false },
    { label: "Curators", href: "/curators", comingSoon: false },
    { label: "Venues", href: "/venues", comingSoon: false },
    { label: "About us", href: "/about", comingSoon: false },
    { label: "Register", href: "/register", comingSoon: false },
    // { label: "FAQ", href: "/faq", comingSoon: false },
    { label: "Contact", href: "/contact", comingSoon: false },
    // { label: "Privacy", href: "/privacy", comingSoon: false },
    // { label: "Terms & Conditions", href: "/terms", comingSoon: false },
  ],
  footer: {
    navigation: [
      { label: "Programmes", href: "/programmes" },
      { label: "Curators", href: "/curators" },
      { label: "Venues", href: "/venues" },
      { label: "About us", href: "/about" },
      { label: "Partners", href: "/partners" },
      { label: "FAQ", href: "/faq" },
      { label: "Contact", href: "/contact" },
      { label: "Terms & Conditions", href: "/terms" },
    ],
    socialLinks: [
      { label: "Instagram", href: "https://www.instagram.com/serendipityartsfestival/" },
      { label: "YouTube", href: "https://www.youtube.com/@SerendipityArtsFestival" },
      { label: "X / Twitter", href: "https://x.com/serendipityartf" },
    ],
    legalLinks: [
      { label: "Privacy", href: "/privacy" },
      { label: "Terms", href: "/terms" },
    ],
    archives: [
      { year: "2025", href: "https://archive2025.serendipityartsfestival.com/" },
      { year: "2024", href: "https://archive2024.serendipityartsfestival.com/" },
      { year: "2023", href: "https://archive2023.serendipityartsfestival.com/" },
      {
        year: "2022",
        href: "https://serendipityarts.org/wp-content/uploads/2025/06/SAF-2022.pdf",
        note: "catalogue",
      },
      { year: "2021", href: "https://serendipityartsvirtual.com/#home/projects" },
      { year: "2020", href: "https://www.serendipityartsfestival-safxyou.com/" },
      {
        year: "2019",
        href: "https://archive.serendipityartsfestival.com/archives-2018/wp-content/uploads/2020/09/Catalogue-SAF-2019-3.pdf",
        note: "catalogue",
      },
      { year: "2018", href: "https://archive2018.serendipityartsfestival.com/" },
      { year: "2017", href: "https://archive2017.serendipityartsfestival.com/" },
      { year: "2016", href: "https://archive2016.serendipityartsfestival.com/" },
    ],
  },
} as const;
