/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SeaRouteImport } from './routes/sea'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CuratorsRouteImport } from './routes/curators'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgrammesCategoryRouteImport } from './routes/programmes.$category'
import { Route as CartAddedRouteImport } from './routes/cart.added'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SeaRoute = SeaRouteImport.update({
  id: '/sea',
  path: '/sea',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CuratorsRoute = CuratorsRouteImport.update({
  id: '/curators',
  path: '/curators',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesCategoryRoute = ProgrammesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ProgrammesRoute,
} as any)
const CartAddedRoute = CartAddedRouteImport.update({
  id: '/added',
  path: '/added',
  getParentRoute: () => CartRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/cart': typeof CartRouteWithChildren
  '/contact': typeof ContactRoute
  '/curators': typeof CuratorsRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/recommend': typeof RecommendRoute
  '/register': typeof RegisterRoute
  '/sea': typeof SeaRoute
  '/terms': typeof TermsRoute
  '/venues': typeof VenuesRoute
  '/volunteer': typeof VolunteerRoute
  '/cart/added': typeof CartAddedRoute
  '/programmes/$category': typeof ProgrammesCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/cart': typeof CartRouteWithChildren
  '/contact': typeof ContactRoute
  '/curators': typeof CuratorsRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/recommend': typeof RecommendRoute
  '/register': typeof RegisterRoute
  '/sea': typeof SeaRoute
  '/terms': typeof TermsRoute
  '/venues': typeof VenuesRoute
  '/volunteer': typeof VolunteerRoute
  '/cart/added': typeof CartAddedRoute
  '/programmes/$category': typeof ProgrammesCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/cart': typeof CartRouteWithChildren
  '/contact': typeof ContactRoute
  '/curators': typeof CuratorsRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/recommend': typeof RecommendRoute
  '/register': typeof RegisterRoute
  '/sea': typeof SeaRoute
  '/terms': typeof TermsRoute
  '/venues': typeof VenuesRoute
  '/volunteer': typeof VolunteerRoute
  '/cart/added': typeof CartAddedRoute
  '/programmes/$category': typeof ProgrammesCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/cart'
    | '/contact'
    | '/curators'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/partners'
    | '/privacy'
    | '/programmes'
    | '/recommend'
    | '/register'
    | '/sea'
    | '/terms'
    | '/venues'
    | '/volunteer'
    | '/cart/added'
    | '/programmes/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/cart'
    | '/contact'
    | '/curators'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/partners'
    | '/privacy'
    | '/programmes'
    | '/recommend'
    | '/register'
    | '/sea'
    | '/terms'
    | '/venues'
    | '/volunteer'
    | '/cart/added'
    | '/programmes/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/cart'
    | '/contact'
    | '/curators'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/partners'
    | '/privacy'
    | '/programmes'
    | '/recommend'
    | '/register'
    | '/sea'
    | '/terms'
    | '/venues'
    | '/volunteer'
    | '/cart/added'
    | '/programmes/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  CartRoute: typeof CartRouteWithChildren
  ContactRoute: typeof ContactRoute
  CuratorsRoute: typeof CuratorsRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgrammesRoute: typeof ProgrammesRouteWithChildren
  RecommendRoute: typeof RecommendRoute
  RegisterRoute: typeof RegisterRoute
  SeaRoute: typeof SeaRoute
  TermsRoute: typeof TermsRoute
  VenuesRoute: typeof VenuesRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sea': {
      id: '/sea'
      path: '/sea'
      fullPath: '/sea'
      preLoaderRoute: typeof SeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curators': {
      id: '/curators'
      path: '/curators'
      fullPath: '/curators'
      preLoaderRoute: typeof CuratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$category': {
      id: '/programmes/$category'
      path: '/$category'
      fullPath: '/programmes/$category'
      preLoaderRoute: typeof ProgrammesCategoryRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/cart/added': {
      id: '/cart/added'
      path: '/added'
      fullPath: '/cart/added'
      preLoaderRoute: typeof CartAddedRouteImport
      parentRoute: typeof CartRoute
    }
  }
}

interface CartRouteChildren {
  CartAddedRoute: typeof CartAddedRoute
}

const CartRouteChildren: CartRouteChildren = {
  CartAddedRoute: CartAddedRoute,
}

const CartRouteWithChildren = CartRoute._addFileChildren(CartRouteChildren)

interface ProgrammesRouteChildren {
  ProgrammesCategoryRoute: typeof ProgrammesCategoryRoute
}

const ProgrammesRouteChildren: ProgrammesRouteChildren = {
  ProgrammesCategoryRoute: ProgrammesCategoryRoute,
}

const ProgrammesRouteWithChildren = ProgrammesRoute._addFileChildren(
  ProgrammesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  CartRoute: CartRouteWithChildren,
  ContactRoute: ContactRoute,
  CuratorsRoute: CuratorsRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ProgrammesRoute: ProgrammesRouteWithChildren,
  RecommendRoute: RecommendRoute,
  RegisterRoute: RegisterRoute,
  SeaRoute: SeaRoute,
  TermsRoute: TermsRoute,
  VenuesRoute: VenuesRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
